Remove conda clean up

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -359,10 +359,10 @@ runs:
       shell: bash
       run: rm -rf ${{ github.workspace }}/*
 
-    - name: Cleanup Conda
-      if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
-      shell: bash -el {0}
-      run: conda deactivate && conda env remove --name comfyui && conda clean -all
+    # - name: Cleanup Conda
+    #   if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
+    #   shell: bash -el {0}
+    #   run: conda deactivate && conda env remove --name comfyui && conda clean -all
 
     ## Windows Cleanup Steps
     - name: Cleanup output files only
