Remove debugging and add clean up

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -35,13 +35,12 @@ runs:
       with:
         miniconda-version: latest
         activate-environment: comfyui
-        auto-activate-base: false
 
-    - name: Sleep for debugging windows
-      if: ${{ inputs.os == 'windows' && failure() }}
-      run: |
-        Start-Sleep -Seconds 3600 # Sleeps for 1 hour
-      shell: powershell
+    # - name: Sleep for debugging windows
+    #   if: ${{ inputs.os == 'windows' && failure() }}
+    #   run: |
+    #     Start-Sleep -Seconds 3600 # Sleeps for 1 hour
+    #   shell: powershell
     
     - name: Install Pytorch nightly for macOS.
       if: ${{ inputs.os == 'macos' }}
@@ -184,3 +183,10 @@ runs:
       if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
       shell: bash -el {0}
       run: conda deactivate && conda env remove --name comfyui
+
+    - name: Cleanup Conda
+      if: ${{ inputs.os == 'windows' && ( success() || failure() ) }}
+      shell: powershell
+      run: |
+        conda deactivate
+        conda env remove --name comfyui
