Fix main.py not found

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -127,7 +127,7 @@ runs:
       if: ${{ inputs.os == 'windows' }}
       shell: powershell
       run: |
-        Start-Job { python main.py --force-fp16 *> application.log }
+        Start-Job { python $Env:GITHUB_WORKSPACE/main.py --force-fp16 *> application.log }
 
     - name: Check if the server is running
       if: ${{ inputs.os != 'windows' }}
@@ -193,7 +193,7 @@ runs:
       shell: powershell
       run: Remove-Item -Path "${{ github.workspace }}/*" -Recurse -Force
 
-    - name: Cleanup Conda
-      if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
-      shell: bash -el {0}
-      run: conda deactivate && conda env remove --name comfyui
+    # - name: Cleanup Conda
+    #   if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
+    #   shell: bash -el {0}
+    #   run: conda deactivate && conda env remove --name comfyui
