Deactivate cleanup.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -199,15 +199,15 @@ runs:
         name: app-logs-${{ github.job }}-${{ inputs.os }}-${{inputs.workflow_name}}-${{ github.run_id }}
         path: ${{ github.workspace }}/application.log
 
-    - name: '[Unix] Cleanup Repo'
-      if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
-      shell: bash -el {0}
-      run: rm -rf ${{ github.workspace }}/*
+    # - name: '[Unix] Cleanup Repo'
+    #   if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
+    #   shell: bash -el {0}
+    #   run: rm -rf ${{ github.workspace }}/*
 
-    - name: '[Unix] Cleanup Conda'
-      if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
-      shell: bash -el {0}
-      run: conda deactivate && conda env remove --name comfyui && conda clean -all
+    # - name: '[Unix] Cleanup Conda'
+    #   if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
+    #   shell: bash -el {0}
+    #   run: conda deactivate && conda env remove --name comfyui && conda clean -all
 
 
     #####################################################################################
